version: '3.0'

services:
  service:
    build: .
    ports:
      - '3333:3000'
    volumes:
      - '/mnt/cache/SSD:/data'
      - '/mnt/user/appdata/whaledeployer:/config'
      - '/var/run/docker.sock:/var/run/docker.sock'
